import "./globals.css";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { ReactNode } from "react";
import TopAppBar from "@/components/top-app-bar/top-app-bar.component";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: {
  children: ReactNode
}) {
  return (
    <html lang="en">
    <body className={`${roboto.className} bg-neutral-950`}>
    <TopAppBar />
    <main className={"pt-[90px]"}>
      {children}
    </main>
    </body>
    </html>
  );
}
